### ISSUE TITLE
Private moon-run dependency

### ISSUE THREAD

**Issue by IBwWG** [profound7/moon-core#5]
Thanks for releasing this!  Looks like a tonne of cool stuff in here!

Trying to run the core.hxproj included in this repo on haxe 3.2.1 (is that an OK version of Haxe to use BTW?)

```
Running process: C:\Program Files (x86)\FlashDevelop\Tools\fdbuild\fdbuild.exe "C:\HaxeToolkit\haxe\lib\moon-core\1,0,0\core.hxproj" -ipc 954b063b-9fb1-4390-8cce-9178b960e864 -version "3.2.1" -compiler "C:\HaxeToolkit\haxe" -notrace -library "C:\Program Files (x86)\FlashDevelop\Library"
Building core
Running Pre-Build Command Line...
cmd: haxelib run moon-run build "Neko"
Library moon-run is not installed
Build halted with errors.
Done(1)
```

`moon-run` doesn't seem to be available from haxelib.  :)

**Comment by profound7** [comment]
Hi, sorry for the late response. It's mostly tested on 3.2, so it's an ok version of Haxe to use. 3.3 should work too.

From the command line, you can run this to test:

``` bash
haxe -main AsyncSugaredExamples -cp src -cp test -neko async.n
neko async
```

But if you want to run it from FlashDevelop, I've also just released moon-run. It's available on [haxelib](http://lib.haxe.org/p/moon-run/0.1.0/) and [github](https://github.com/profound7/moon-run).
